name: memespin
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/YOUR_GITHUB_USERNAME/memespin.git
    build_command: npm run build
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs 